import ModifierHelpers from "../modules/helpers/modifiers.js";

export const ModifiersTests = (suite, suiteInstance, Test, chai) => {
  const _suite = suiteInstance.create(suite, `Modifier Helpers`);

  _suite.addTest(
    new Test("Should calculate value from attributes and items", function () {
      const attributes = {
        "Brawn": {
          "modtype": "Characteristic",
          "value": 1,
          "mod": "Brawn",
          "key": "Brawn",
        },
      };
      const items = [
        {
          "_id": "CRwhafuF4R6uMAwe",
          "name": "Defel",
          "type": "species",
          "data": {
            "description": "<h4>Abilities</h4><p>Light Sensitive : In bright light, without protective goggles,\n            Defel suffer [SETBACK][SETBACK] on all skill checks.</p><p>Shadowed : In darkness, Defel gain [BOOST][BOOST]\n            to Stealth checks.</p><p>Reduced Silhouette : Defel have a Silhouette of 0.</p><p></p>[H4]Defel[h4]\n\nThe Defel (colloquially known as Wraiths) are barely visible beings native to the Outer Rim planet Af'El who appear to most other species as shadows, re-enforcing the misconception that they are chameleon-like beings or \"living shadows\".\n\n[P][B]Physiology:[b] Defel are from Af'El, a large, high-gravity, seldom-visited world orbiting the ultraviolet supergiant Ka'Dedus. Since Af'El has no ozone layer, ultraviolet light passes freely to the surface, while other light wavelengths are mostly blocked by the heavy gases in the planet's atmosphere. Thus, all lifeforms on Af'El can see in ultraviolet light ranges, but are blinded by all but the dimmest light in other wavelengths. This is why Defels normally wear a visor when they leave Af'El, and expect to be exposed to daylight at their destination. Compared to other species, they can see exceptionally well in the dark.\n\n[P]Defel are short, stocky beings, averaging 1.3 meters tall and nearly as wide. Though they are nearly invisible in normal light, Defel are actually colorful beings. Viewed under ultraviolet light, their fur appear in colors ranging from yellow to blue. Their snouts appear green, with orange, gill-like slits at the base of their jawlines. Elderly Defel lose their ability to absorb light, fading to a dull dark brown under visible light.\n\n[P][B]Society:[b] Due to the harsh conditions of Af'El, Defel have a society based on communal resource sharing. Co-operation is vital for survival. As a result, the typical Defel is a tough, independent being, with a strong sense of honor. Defel stand by their word, and refuse to associate with anyone who has broken a promise. The Defel live in underground cities to escape Af'El's violent storms. Their subterranean society has developed highly advanced mining and metallurgical technology, though they have not developed space travel or agriculture on their own.\n\n[P]Their homeworld is seldom visited due to the difficulty of escaping its gravity well, making Defel rare outside of the Ka'Dedus system. This rarity, combined with their unusual abilities, mean that much of the galaxy believes they are mythical or supernatural beings. Some of the few Defel who leave their homeworld go in search of adventure, and often employ their natural stealth abilities to become assassins, bodyguards, or thieves. Most Defel who leave Af'El, however, are prized more for their skills in metallurgy, and are contracted by smelting operations and starship manufacturers.\n\n[P]The Defel see some trade in meleenium, a rare substance used in durasteel production, which is only found naturally on Af'El. Vulca Minerals sends one ship a year to the Defel to trade fresh food for meleenium.\n\n[P][B]Homeworld:[b] Af'El is the homeworld to the Defel, whom dwell in underground cities. It is a high-gravity planet with no ozone layer, and it orbits the ultraviolet supergiant Ka'Dedus. Because of the lack of ozone, ultraviolet light passed freely to the surface, while other light wavelengths are blocked by the heavy gases in the planet's atmosphere. Thus, all animals on Af'El can only see in ultraviolet light ranges. A main export of the planet is the metal meleenium used in durasteel.\n\n[P]Due to the tremendous velocity necessary for a starship to escape Af'El's gravity well, the planet was rarely visited. It was the only known source of naturally occurring meleenium, and as a result, Vulca Minerals made annual trips to the world. A number of private metallurgists and scientists also visited the world to conduct research.\n\n[P][B]Language:[b] Defel is the official language of Af'El, used by the native Defel species. Defels are not fond of languages other than their own, so most of them do not learn  Galactic Basic Standard unless they have need for it, mainly because they need to leave  Af'El. Ironically, more often than not, it is easy to find a Basic-speaking Defel (other than  the difficult task of finding a Defel at all).",
            "attributes": {
              "Brawn": {
                "mod": "Brawn",
                "modtype": "Characteristic",
                "value": 2,
                "exclude": true,
              },
              "Agility": {
                "mod": "Agility",
                "modtype": "Characteristic",
                "value": 2,
                "exclude": true,
              },
              "Intellect": {
                "mod": "Intellect",
                "modtype": "Characteristic",
                "value": 1,
                "exclude": true,
              },
              "Cunning": {
                "mod": "Cunning",
                "modtype": "Characteristic",
                "value": 3,
                "exclude": true,
              },
              "Willpower": {
                "mod": "Willpower",
                "modtype": "Characteristic",
                "value": 2,
                "exclude": true,
              },
              "Presence": {
                "mod": "Presence",
                "modtype": "Characteristic",
                "value": 2,
                "exclude": true,
              },
              "Wounds": {
                "mod": "Wounds",
                "modtype": "Stat",
                "value": 10,
                "exclude": true,
              },
              "Strain": {
                "mod": "Strain",
                "modtype": "Stat",
                "value": 10,
                "exclude": true,
              },
              "Vigilance": {
                "mod": "Vigilance",
                "modtype": "Skill Rank",
                "value": 1,
                "exclude": false,
              },
            },
            "renderedDesc": "<h4>Abilities</h4><p>Light Sensitive : In bright light, without protective goggles,\n            Defel suffer <span class='dietype starwars setback'>b</span><span class='dietype starwars setback'>b</span> on all skill checks.</p><p>Shadowed : In darkness, Defel gain <span class='dietype starwars boost'>b</span><span class='dietype starwars boost'>b</span>\n            to Stealth checks.</p><p>Reduced Silhouette : Defel have a Silhouette of 0.</p><p></p><h4>Defel</h4>\n\nThe Defel (colloquially known as Wraiths) are barely visible beings native to the Outer Rim planet Af'El who appear to most other species as shadows, re-enforcing the misconception that they are chameleon-like beings or \"living shadows\".\n\n<p><span class='bold'>Physiology:</span> Defel are from Af'El, a large, high-gravity, seldom-visited world orbiting the ultraviolet supergiant Ka'Dedus. Since Af'El has no ozone layer, ultraviolet light passes freely to the surface, while other light wavelengths are mostly blocked by the heavy gases in the planet's atmosphere. Thus, all lifeforms on Af'El can see in ultraviolet light ranges, but are blinded by all but the dimmest light in other wavelengths. This is why Defels normally wear a visor when they leave Af'El, and expect to be exposed to daylight at their destination. Compared to other species, they can see exceptionally well in the dark.\n\n</p><p>Defel are short, stocky beings, averaging 1.3 meters tall and nearly as wide. Though they are nearly invisible in normal light, Defel are actually colorful beings. Viewed under ultraviolet light, their fur appear in colors ranging from yellow to blue. Their snouts appear green, with orange, gill-like slits at the base of their jawlines. Elderly Defel lose their ability to absorb light, fading to a dull dark brown under visible light.\n\n</p><p><span class='bold'>Society:</span> Due to the harsh conditions of Af'El, Defel have a society based on communal resource sharing. Co-operation is vital for survival. As a result, the typical Defel is a tough, independent being, with a strong sense of honor. Defel stand by their word, and refuse to associate with anyone who has broken a promise. The Defel live in underground cities to escape Af'El's violent storms. Their subterranean society has developed highly advanced mining and metallurgical technology, though they have not developed space travel or agriculture on their own.\n\n</p><p>Their homeworld is seldom visited due to the difficulty of escaping its gravity well, making Defel rare outside of the Ka'Dedus system. This rarity, combined with their unusual abilities, mean that much of the galaxy believes they are mythical or supernatural beings. Some of the few Defel who leave their homeworld go in search of adventure, and often employ their natural stealth abilities to become assassins, bodyguards, or thieves. Most Defel who leave Af'El, however, are prized more for their skills in metallurgy, and are contracted by smelting operations and starship manufacturers.\n\n</p><p>The Defel see some trade in meleenium, a rare substance used in durasteel production, which is only found naturally on Af'El. Vulca Minerals sends one ship a year to the Defel to trade fresh food for meleenium.\n\n</p><p><span class='bold'>Homeworld:</span> Af'El is the homeworld to the Defel, whom dwell in underground cities. It is a high-gravity planet with no ozone layer, and it orbits the ultraviolet supergiant Ka'Dedus. Because of the lack of ozone, ultraviolet light passed freely to the surface, while other light wavelengths are blocked by the heavy gases in the planet's atmosphere. Thus, all animals on Af'El can only see in ultraviolet light ranges. A main export of the planet is the metal meleenium used in durasteel.\n\n</p><p>Due to the tremendous velocity necessary for a starship to escape Af'El's gravity well, the planet was rarely visited. It was the only known source of naturally occurring meleenium, and as a result, Vulca Minerals made annual trips to the world. A number of private metallurgists and scientists also visited the world to conduct research.\n\n</p><p><span class='bold'>Language:</span> Defel is the official language of Af'El, used by the native Defel species. Defels are not fond of languages other than their own, so most of them do not learn  Galactic Basic Standard unless they have need for it, mainly because they need to leave  Af'El. Ironically, more often than not, it is easy to find a Basic-speaking Defel (other than  the difficult task of finding a Defel at all).</p>",
          },
          "flags": {
            "importid": "DEFEL",
          },
          "img": "modules/starwarsffg-compendiums/images/packs/oggdudespecies/DEFEL.png",
          "effects": [],
        },
        {
          "_id": "WOIux8jzLP1QZYEl",
          "name": "Shii-Cho Knight",
          "type": "specialization",
          "data": {
            "description": "[H4]Shii-Cho Knight[h4]\n\nThe ancient lightsaber fighting style of Shii-Cho is said to be the first lightsaber form taught to the Jedi and their predecessors. It focuses on the essentials of saber fighting and borrows heavily from other sword fighting techniques. Appropriately, the modern practitioners of this form focus on perfecting the core tenants of sword fighting, recognizing the strength of simplicity. Shii-Cho Knights eschew fancy maneuvers, preferring to focus on the fundamentals of block, parry. and strike.\n\n[P]Shii-Cho Knights acquire [B]Athletics, Coordination, Lightsaber,[b] and [B]Melee[b] as additional career skills. If this is the character's starting specialization, he may choose two of these skills and gain one free rank in each, without spending starting experience. These skills provide them with a solid grounding in the core techniques of any physical conflict. They are familiar with the weapon they wield, but they are also very comfortable exploiting their natural athleticism and flexibility. Because of this, they can not only avoid an enemy's attack, but also make certain that they are able to strike effectively when their target is at a disadvantage.\n\n[P]Followers of this path are seldom concerned with personal appearances or the style that they exhibit in a conflict. Instead, they are focused on precision and on achieving their ultimate goal of victory. For them, a solid grounding in the basics is something they can rely on in any situation. When lives are on the line, they devote their attention to executing their maneuvers in a traditional way, using them to counter an opponent while simultaneously restricting his options.",
            "attributes": {
              "attr1": {
                "mod": "Athletics",
                "modtype": "Career Skill",
                "value": true,
              },
              "attr2": {
                "mod": "Athletics",
                "modtype": "Skill Rank",
                "value": 0,
              },
              "attr3": {
                "mod": "Coordination",
                "modtype": "Career Skill",
                "value": true,
              },
              "attr4": {
                "mod": "Coordination",
                "modtype": "Skill Rank",
                "value": 0,
              },
              "attr5": {
                "mod": "Lightsaber",
                "modtype": "Career Skill",
                "value": true,
              },
              "attr6": {
                "mod": "Lightsaber",
                "modtype": "Skill Rank",
                "value": 1,
                "key": "Lightsaber",
              },
              "attr7": {
                "mod": "Melee",
                "modtype": "Career Skill",
                "value": true,
              },
              "attr8": {
                "mod": "Melee",
                "modtype": "Skill Rank",
                "value": 1,
                "key": "Melee",
              },
              "attrForceRating": {
                "mod": "ForcePool",
                "modtype": "Stat",
                "value": 1,
              },
            },
            "talents": {
              "talent0": {
                "name": "Parry",
                "description": "When hit by a melee attack, suffer 3 strain to reduce damage by 2 plus ranks in Parry.",
                "activation": "Active (Incidental, Out of Turn)",
                "activationLabel": "SWFFG.TalentActivationsActiveIncidentalOutofTurn",
                "isForceTalent": false,
                "isRanked": true,
                "size": "single",
                "canLinkTop": true,
                "canLinkRight": true,
                "itemId": "EFL2xt5A365PdhfQ",
                "attributes": {},
                "pack": "world.oggdudetalents",
                "isConflictTalent": false,
                "rank": 1,
                "islearned": true,
                "cost": "5",
                "links-top-1": false,
                "links-right": false,
                "visible": true,
                "canSplit": false,
                "canCombine": true,
              },
              "talent1": {
                "name": "Second Wind",
                "description": "Once per encounter, may use Second Wind incidental to heal strain equal to ranks in Second Wind.",
                "activation": "Active (Incidental)",
                "activationLabel": "SWFFG.TalentActivationsActiveIncidental",
                "isForceTalent": false,
                "isRanked": true,
                "size": "single",
                "canLinkTop": true,
                "canLinkRight": true,
                "itemId": "Jg87sIssUR7t5nP9",
                "attributes": {},
                "pack": "world.oggdudetalents",
                "isConflictTalent": false,
                "rank": 1,
                "islearned": true,
                "cost": "5",
                "links-top-1": false,
                "links-right": false,
                "visible": true,
                "canSplit": false,
                "canCombine": true,
              },
              "talent2": {
                "name": "Toughened",
                "description": "Gain +2 wound threshold.",
                "activation": "Passive",
                "activationLabel": "SWFFG.TalentActivationsPassive",
                "isForceTalent": false,
                "isRanked": true,
                "size": "single",
                "canLinkTop": true,
                "canLinkRight": true,
                "itemId": "pHVUWrmAS4iHuWis",
                "attributes": {
                  "Wounds": {
                    "mod": "Wounds",
                    "modtype": "Stat",
                    "value": "2",
                  },
                },
                "pack": "world.oggdudetalents",
                "isConflictTalent": false,
                "rank": 1,
                "islearned": true,
                "cost": "5",
                "links-top-1": false,
                "links-right": false,
                "visible": true,
                "canSplit": false,
                "canCombine": true,
              },
              "talent3": {
                "name": "Parry",
                "description": "When hit by a melee attack, suffer 3 strain to reduce damage by 2 plus ranks in Parry.",
                "activation": "Active (Incidental, Out of Turn)",
                "activationLabel": "SWFFG.TalentActivationsActiveIncidentalOutofTurn",
                "isForceTalent": false,
                "isRanked": true,
                "size": "single",
                "canLinkTop": true,
                "canLinkRight": false,
                "itemId": "EFL2xt5A365PdhfQ",
                "attributes": {},
                "pack": "world.oggdudetalents",
                "isConflictTalent": false,
                "rank": 1,
                "islearned": true,
                "cost": "5",
                "links-top-1": false,
                "links-right": false,
                "visible": true,
                "canSplit": false,
                "canCombine": false,
              },
              "talent4": {
                "name": "Second Wind",
                "description": "Once per encounter, may use Second Wind incidental to heal strain equal to ranks in Second Wind.",
                "activation": "Active (Incidental)",
                "activationLabel": "SWFFG.TalentActivationsActiveIncidental",
                "isForceTalent": false,
                "isRanked": true,
                "size": "single",
                "canLinkTop": true,
                "canLinkRight": true,
                "itemId": "Jg87sIssUR7t5nP9",
                "attributes": {},
                "links-top-1": true,
                "links-right": true,
                "pack": "world.oggdudetalents",
                "isConflictTalent": false,
                "rank": 1,
                "islearned": true,
                "cost": "10",
                "visible": true,
                "canSplit": false,
                "canCombine": true,
              },
              "talent5": {
                "name": "Conditioned",
                "description": "Remove [SE] per rank of Conditioned from Athletics and Coordination check. Reduce the damage and strain suffered from falling by 1 per rank of Conditioned.",
                "activation": "Passive",
                "activationLabel": "SWFFG.TalentActivationsPassive",
                "isForceTalent": false,
                "isRanked": false,
                "size": "single",
                "canLinkTop": true,
                "canLinkRight": true,
                "itemId": "yvoZZSmBhVV653hW",
                "attributes": {
                  "attr1": {
                    "mod": "Athletics",
                    "modtype": "Skill Remove Setback",
                    "value": "1",
                  },
                  "attr2": {
                    "mod": "Coordination",
                    "modtype": "Skill Remove Setback",
                    "value": "1",
                  },
                  "Athletics": {
                    "mod": "Athletics",
                    "modtype": "Skill Remove Setback",
                    "value": 1,
                  },
                  "Coordination": {
                    "mod": "Coordination",
                    "modtype": "Skill Remove Setback",
                    "value": 1,
                  },
                },
                "links-top-1": true,
                "links-right": true,
                "pack": "world.oggdudetalents",
                "isConflictTalent": false,
                "islearned": false,
                "cost": "10",
                "visible": true,
                "canSplit": false,
                "canCombine": true,
              },
              "talent6": {
                "name": "Multiple Opponents",
                "description": "Add [BO] to Lightsaber, Brawl, and Melee checks when engaged with multiple opponents.",
                "activation": "Passive",
                "activationLabel": "SWFFG.TalentActivationsPassive",
                "isForceTalent": false,
                "isRanked": false,
                "size": "single",
                "canLinkTop": true,
                "canLinkRight": true,
                "itemId": "o5MSc9SAbVFmY3KF",
                "attributes": {},
                "links-top-1": true,
                "pack": "world.oggdudetalents",
                "isConflictTalent": false,
                "rank": 1,
                "islearned": true,
                "cost": "10",
                "links-right": false,
                "visible": true,
                "canSplit": false,
                "canCombine": true,
              },
              "talent7": {
                "name": "Durable",
                "description": "May reduce any Critical Injury suffered by 10 per rank of Durable to a minimum of 1.",
                "activation": "Passive",
                "activationLabel": "SWFFG.TalentActivationsPassive",
                "isForceTalent": false,
                "isRanked": false,
                "size": "single",
                "canLinkTop": true,
                "canLinkRight": false,
                "itemId": "3dxGgVswF83a6qjU",
                "attributes": {},
                "links-top-1": true,
                "pack": "world.oggdudetalents",
                "isConflictTalent": false,
                "islearned": false,
                "cost": "10",
                "links-right": false,
                "visible": true,
                "canSplit": false,
                "canCombine": false,
              },
              "talent8": {
                "name": "Quick Draw",
                "description": "Once per round, draw or holster a weapon or accessible item as an incidental.",
                "activation": "Active (Incidental)",
                "activationLabel": "SWFFG.TalentActivationsActiveIncidental",
                "isForceTalent": false,
                "isRanked": false,
                "size": "single",
                "canLinkTop": true,
                "canLinkRight": true,
                "itemId": "Ae0lmgBU0cdoI7ss",
                "attributes": {},
                "links-top-1": true,
                "pack": "world.oggdudetalents",
                "isConflictTalent": false,
                "islearned": false,
                "cost": "15",
                "links-right": false,
                "visible": true,
                "canSplit": false,
                "canCombine": true,
              },
              "talent9": {
                "name": "Grit",
                "description": "Gain +1 strain threshold",
                "activation": "Passive",
                "activationLabel": "SWFFG.TalentActivationsPassive",
                "isForceTalent": false,
                "isRanked": true,
                "size": "single",
                "canLinkTop": true,
                "canLinkRight": true,
                "itemId": "AMrvdqjdqfqfJQLJ",
                "attributes": {
                  "Strain": {
                    "mod": "Strain",
                    "modtype": "Stat",
                    "value": "1",
                  },
                },
                "links-top-1": true,
                "links-right": true,
                "pack": "world.oggdudetalents",
                "isConflictTalent": false,
                "rank": 1,
                "islearned": true,
                "cost": "15",
                "visible": true,
                "canSplit": false,
                "canCombine": true,
              },
              "talent10": {
                "name": "Parry",
                "description": "When hit by a melee attack, suffer 3 strain to reduce damage by 2 plus ranks in Parry.",
                "activation": "Active (Incidental, Out of Turn)",
                "activationLabel": "SWFFG.TalentActivationsActiveIncidentalOutofTurn",
                "isForceTalent": false,
                "isRanked": true,
                "size": "single",
                "canLinkTop": true,
                "canLinkRight": true,
                "itemId": "EFL2xt5A365PdhfQ",
                "attributes": {},
                "links-top-1": true,
                "links-right": true,
                "pack": "world.oggdudetalents",
                "isConflictTalent": false,
                "rank": 1,
                "islearned": true,
                "cost": "15",
                "visible": true,
                "canSplit": false,
                "canCombine": true,
              },
              "talent11": {
                "name": "Defensive Training",
                "description": "When wielding a Lightsaber, Melee, or Brawl weapon, the weapon gains the Defensive quality with a rating equal to ranks in Defensive Training.",
                "activation": "Passive",
                "activationLabel": "SWFFG.TalentActivationsPassive",
                "isForceTalent": false,
                "isRanked": false,
                "size": "single",
                "canLinkTop": true,
                "canLinkRight": false,
                "itemId": "wXWdbsJt5ILPjrMq",
                "attributes": {},
                "links-top-1": true,
                "pack": "world.oggdudetalents",
                "isConflictTalent": false,
                "islearned": false,
                "cost": "15",
                "links-right": false,
                "visible": true,
                "canSplit": false,
                "canCombine": false,
              },
              "talent12": {
                "name": "Natural Blademaster",
                "description": "Once per session, may reroll any 1 Lightsaber or Melee check.",
                "activation": "Active (Incidental)",
                "activationLabel": "SWFFG.TalentActivationsActiveIncidental",
                "isForceTalent": false,
                "isRanked": false,
                "size": "single",
                "canLinkTop": true,
                "canLinkRight": true,
                "itemId": "O5aGkqYoUrWgpwZi",
                "attributes": {},
                "links-top-1": true,
                "links-right": true,
                "pack": "world.oggdudetalents",
                "isConflictTalent": false,
                "islearned": false,
                "cost": "20",
                "visible": true,
                "canSplit": false,
                "canCombine": true,
              },
              "talent13": {
                "name": "Sarlacc Sweep",
                "description": "Increase difficulty of Lightsaber check by 1 to perform Sarlacc Sweep action. May spend [AD][AD] to hit additional engaged targets.",
                "activation": "Active (Action)",
                "activationLabel": "SWFFG.TalentActivationsActiveAction",
                "isForceTalent": false,
                "isRanked": false,
                "size": "single",
                "canLinkTop": true,
                "canLinkRight": true,
                "itemId": "AChMkpSpNq2TfGss",
                "attributes": {},
                "links-top-1": true,
                "pack": "world.oggdudetalents",
                "isConflictTalent": false,
                "rank": 1,
                "islearned": true,
                "cost": "20",
                "links-right": false,
                "visible": true,
                "canSplit": false,
                "canCombine": true,
              },
              "talent14": {
                "name": "Parry (Improved)",
                "description": "When parrying a hit that generate [DE] or [TH][TH][TH], may hit attacker once with Lightsaber, Brawl, or Melee weapon (dealing base damage) after original attack resolves.",
                "activation": "Active (Incidental, Out of Turn)",
                "activationLabel": "SWFFG.TalentActivationsActiveIncidentalOutofTurn",
                "isForceTalent": false,
                "isRanked": false,
                "size": "single",
                "canLinkTop": true,
                "canLinkRight": true,
                "itemId": "YIttPgrGqB8FMY3j",
                "attributes": {},
                "links-top-1": true,
                "links-right": true,
                "pack": "world.oggdudetalents",
                "isConflictTalent": false,
                "islearned": false,
                "cost": "20",
                "visible": true,
                "canSplit": false,
                "canCombine": true,
              },
              "talent15": {
                "name": "Sum Djem",
                "description": "May spend [TR] or [AD][AD] with a successful Lightsaber check to disarm opponent.",
                "activation": "Passive",
                "activationLabel": "SWFFG.TalentActivationsPassive",
                "isForceTalent": false,
                "isRanked": false,
                "size": "single",
                "canLinkTop": true,
                "canLinkRight": false,
                "itemId": "7ZnTrrlAQHHsh5PC",
                "attributes": {},
                "links-top-1": true,
                "pack": "world.oggdudetalents",
                "isConflictTalent": false,
                "islearned": false,
                "cost": "20",
                "links-right": false,
                "visible": true,
                "canSplit": false,
                "canCombine": false,
              },
              "talent16": {
                "name": "Center of Being",
                "description": "Take a Center of Being maneuver. Until the beginning of next turn, attacks against the character increase their critical rating by 1 per rank of Center of Being.",
                "activation": "Active (Maneuver)",
                "activationLabel": "SWFFG.TalentActivationsActiveManeuver",
                "isForceTalent": false,
                "isRanked": false,
                "size": "single",
                "canLinkTop": true,
                "canLinkRight": true,
                "itemId": "JcFo4dDFjdSHTYVt",
                "attributes": {},
                "links-top-1": true,
                "links-right": true,
                "pack": "world.oggdudetalents",
                "isConflictTalent": false,
                "islearned": false,
                "cost": "25",
                "visible": true,
                "canSplit": false,
                "canCombine": true,
              },
              "talent17": {
                "name": "Durable",
                "description": "May reduce any Critical Injury suffered by 10 per rank of Durable to a minimum of 1.",
                "activation": "Passive",
                "activationLabel": "SWFFG.TalentActivationsPassive",
                "isForceTalent": false,
                "isRanked": true,
                "size": "single",
                "canLinkTop": true,
                "canLinkRight": true,
                "itemId": "3dxGgVswF83a6qjU",
                "attributes": {},
                "links-top-1": true,
                "links-right": true,
                "pack": "world.oggdudetalents",
                "isConflictTalent": false,
                "rank": 1,
                "islearned": true,
                "cost": "25",
                "visible": true,
                "canSplit": false,
                "canCombine": true,
              },
              "talent18": {
                "name": "Dedication",
                "description": "Gain +1 to a single characteristic. This cannot bring a characteristic above 6.",
                "activation": "Passive",
                "activationLabel": "SWFFG.TalentActivationsPassive",
                "isForceTalent": false,
                "isRanked": true,
                "size": "single",
                "canLinkTop": true,
                "canLinkRight": true,
                "itemId": "SsEealnoSAxzud0g",
                "attributes": {
                  "attr1": {
                    "isCheckbox": false,
                    "mod": "Brawn",
                    "modtype": "Characteristic",
                    "value": 1,
                  },
                },
                "links-right": true,
                "pack": "world.oggdudetalents",
                "isConflictTalent": false,
                "rank": 1,
                "islearned": true,
                "cost": "25",
                "links-top-1": false,
                "visible": true,
                "canSplit": false,
                "canCombine": true,
              },
              "talent19": {
                "name": "Parry",
                "description": "When hit by a melee attack, suffer 3 strain to reduce damage by 2 plus ranks in Parry.",
                "activation": "Active (Incidental, Out of Turn)",
                "activationLabel": "SWFFG.TalentActivationsActiveIncidentalOutofTurn",
                "isForceTalent": false,
                "isRanked": false,
                "size": "single",
                "canLinkTop": true,
                "canLinkRight": false,
                "itemId": "EFL2xt5A365PdhfQ",
                "attributes": {},
                "pack": "world.oggdudetalents",
                "isConflictTalent": false,
                "islearned": false,
                "cost": "25",
                "links-top-1": false,
                "links-right": false,
                "visible": true,
                "canSplit": false,
                "canCombine": false,
              },
            },
            "careerskills": {},
            "isEditing": false,
            "renderedDesc": "<h4>Shii-Cho Knight</h4>\n\nThe ancient lightsaber fighting style of Shii-Cho is said to be the first lightsaber form taught to the Jedi and their predecessors. It focuses on the essentials of saber fighting and borrows heavily from other sword fighting techniques. Appropriately, the modern practitioners of this form focus on perfecting the core tenants of sword fighting, recognizing the strength of simplicity. Shii-Cho Knights eschew fancy maneuvers, preferring to focus on the fundamentals of block, parry. and strike.\n\n<p>Shii-Cho Knights acquire <span class='bold'>Athletics, Coordination, Lightsaber,</span> and <span class='bold'>Melee</span> as additional career skills. If this is the character's starting specialization, he may choose two of these skills and gain one free rank in each, without spending starting experience. These skills provide them with a solid grounding in the core techniques of any physical conflict. They are familiar with the weapon they wield, but they are also very comfortable exploiting their natural athleticism and flexibility. Because of this, they can not only avoid an enemy's attack, but also make certain that they are able to strike effectively when their target is at a disadvantage.\n\n</p><p>Followers of this path are seldom concerned with personal appearances or the style that they exhibit in a conflict. Instead, they are focused on precision and on achieving their ultimate goal of victory. For them, a solid grounding in the basics is something they can rely on in any situation. When lives are on the line, they devote their attention to executing their maneuvers in a traditional way, using them to counter an opponent while simultaneously restricting his options.</p>",
          },
          "sort": 100000,
          "flags": {
            "importid": "SHIICHO",
          },
          "img": "icons/svg/mystery-man.svg",
          "effects": [],
          "talentList": [
            {
              "name": "Parry",
              "description": "When hit by a melee attack, suffer 3 strain to reduce damage by 2 plus ranks in Parry.",
              "activation": "Active (Incidental, Out of Turn)",
              "activationLabel": "SWFFG.TalentActivationsActiveIncidentalOutofTurn",
              "isForceTalent": false,
              "isRanked": true,
              "size": "single",
              "canLinkTop": true,
              "canLinkRight": true,
              "itemId": "EFL2xt5A365PdhfQ",
              "attributes": {},
              "pack": "world.oggdudetalents",
              "isConflictTalent": false,
              "rank": 3,
              "islearned": true,
              "cost": "5",
              "links-top-1": false,
              "links-right": false,
            },
            {
              "name": "Second Wind",
              "description": "Once per encounter, may use Second Wind incidental to heal strain equal to ranks in Second Wind.",
              "activation": "Active (Incidental)",
              "activationLabel": "SWFFG.TalentActivationsActiveIncidental",
              "isForceTalent": false,
              "isRanked": true,
              "size": "single",
              "canLinkTop": true,
              "canLinkRight": true,
              "itemId": "Jg87sIssUR7t5nP9",
              "attributes": {},
              "pack": "world.oggdudetalents",
              "isConflictTalent": false,
              "rank": 2,
              "islearned": true,
              "cost": "5",
              "links-top-1": false,
              "links-right": false,
            },
            {
              "name": "Toughened",
              "description": "Gain +2 wound threshold.",
              "activation": "Passive",
              "activationLabel": "SWFFG.TalentActivationsPassive",
              "isForceTalent": false,
              "isRanked": true,
              "size": "single",
              "canLinkTop": true,
              "canLinkRight": true,
              "itemId": "pHVUWrmAS4iHuWis",
              "attributes": {
                "Wounds": {
                  "mod": "Wounds",
                  "modtype": "Stat",
                  "value": "2",
                },
              },
              "pack": "world.oggdudetalents",
              "isConflictTalent": false,
              "rank": 1,
              "islearned": true,
              "cost": "5",
              "links-top-1": false,
              "links-right": false,
            },
            {
              "name": "Multiple Opponents",
              "description": "Add [BO] to Lightsaber, Brawl, and Melee checks when engaged with multiple opponents.",
              "activation": "Passive",
              "activationLabel": "SWFFG.TalentActivationsPassive",
              "isForceTalent": false,
              "isRanked": false,
              "size": "single",
              "canLinkTop": true,
              "canLinkRight": true,
              "itemId": "o5MSc9SAbVFmY3KF",
              "attributes": {},
              "links-top-1": true,
              "pack": "world.oggdudetalents",
              "isConflictTalent": false,
              "rank": "N/A",
              "islearned": true,
              "cost": "10",
              "links-right": false,
            },
            {
              "name": "Grit",
              "description": "Gain +1 strain threshold",
              "activation": "Passive",
              "activationLabel": "SWFFG.TalentActivationsPassive",
              "isForceTalent": false,
              "isRanked": true,
              "size": "single",
              "canLinkTop": true,
              "canLinkRight": true,
              "itemId": "AMrvdqjdqfqfJQLJ",
              "attributes": {
                "Strain": {
                  "mod": "Strain",
                  "modtype": "Stat",
                  "value": "1",
                },
              },
              "links-top-1": true,
              "links-right": true,
              "pack": "world.oggdudetalents",
              "isConflictTalent": false,
              "rank": 1,
              "islearned": true,
              "cost": "15",
            },
            {
              "name": "Sarlacc Sweep",
              "description": "Increase difficulty of Lightsaber check by 1 to perform Sarlacc Sweep action. May spend [AD][AD] to hit additional engaged targets.",
              "activation": "Active (Action)",
              "activationLabel": "SWFFG.TalentActivationsActiveAction",
              "isForceTalent": false,
              "isRanked": false,
              "size": "single",
              "canLinkTop": true,
              "canLinkRight": true,
              "itemId": "AChMkpSpNq2TfGss",
              "attributes": {},
              "links-top-1": true,
              "pack": "world.oggdudetalents",
              "isConflictTalent": false,
              "rank": "N/A",
              "islearned": true,
              "cost": "20",
              "links-right": false,
            },
            {
              "name": "Durable",
              "description": "May reduce any Critical Injury suffered by 10 per rank of Durable to a minimum of 1.",
              "activation": "Passive",
              "activationLabel": "SWFFG.TalentActivationsPassive",
              "isForceTalent": false,
              "isRanked": true,
              "size": "single",
              "canLinkTop": true,
              "canLinkRight": true,
              "itemId": "3dxGgVswF83a6qjU",
              "attributes": {},
              "links-top-1": true,
              "links-right": true,
              "pack": "world.oggdudetalents",
              "isConflictTalent": false,
              "rank": 1,
              "islearned": true,
              "cost": "25",
            },
            {
              "name": "Dedication",
              "description": "Gain +1 to a single characteristic. This cannot bring a characteristic above 6.",
              "activation": "Passive",
              "activationLabel": "SWFFG.TalentActivationsPassive",
              "isForceTalent": false,
              "isRanked": true,
              "size": "single",
              "canLinkTop": true,
              "canLinkRight": true,
              "itemId": "SsEealnoSAxzud0g",
              "attributes": {
                "attr1": {
                  "isCheckbox": false,
                  "mod": "Brawn",
                  "modtype": "Characteristic",
                  "value": 1,
                },
              },
              "links-right": true,
              "pack": "world.oggdudetalents",
              "isConflictTalent": false,
              "rank": 1,
              "islearned": true,
              "cost": "25",
              "links-top-1": false,
            },
          ],
        },
      ];
      chai.expect(ModifierHelpers.getCalculateValueForAttribute("Brawn", attributes, items, "Characteristic")).to.equal(4);
    })
  );

  _suite.addTest(
    new Test("Should calculate the base values based only on species", function () {
      const items = [
        {
          "_id": "CRwhafuF4R6uMAwe",
          "name": "Defel",
          "type": "species",
          "data": {
            "description": "<h4>Abilities</h4><p>Light Sensitive : In bright light, without protective goggles,\n            Defel suffer [SETBACK][SETBACK] on all skill checks.</p><p>Shadowed : In darkness, Defel gain [BOOST][BOOST]\n            to Stealth checks.</p><p>Reduced Silhouette : Defel have a Silhouette of 0.</p><p></p>[H4]Defel[h4]\n\nThe Defel (colloquially known as Wraiths) are barely visible beings native to the Outer Rim planet Af'El who appear to most other species as shadows, re-enforcing the misconception that they are chameleon-like beings or \"living shadows\".\n\n[P][B]Physiology:[b] Defel are from Af'El, a large, high-gravity, seldom-visited world orbiting the ultraviolet supergiant Ka'Dedus. Since Af'El has no ozone layer, ultraviolet light passes freely to the surface, while other light wavelengths are mostly blocked by the heavy gases in the planet's atmosphere. Thus, all lifeforms on Af'El can see in ultraviolet light ranges, but are blinded by all but the dimmest light in other wavelengths. This is why Defels normally wear a visor when they leave Af'El, and expect to be exposed to daylight at their destination. Compared to other species, they can see exceptionally well in the dark.\n\n[P]Defel are short, stocky beings, averaging 1.3 meters tall and nearly as wide. Though they are nearly invisible in normal light, Defel are actually colorful beings. Viewed under ultraviolet light, their fur appear in colors ranging from yellow to blue. Their snouts appear green, with orange, gill-like slits at the base of their jawlines. Elderly Defel lose their ability to absorb light, fading to a dull dark brown under visible light.\n\n[P][B]Society:[b] Due to the harsh conditions of Af'El, Defel have a society based on communal resource sharing. Co-operation is vital for survival. As a result, the typical Defel is a tough, independent being, with a strong sense of honor. Defel stand by their word, and refuse to associate with anyone who has broken a promise. The Defel live in underground cities to escape Af'El's violent storms. Their subterranean society has developed highly advanced mining and metallurgical technology, though they have not developed space travel or agriculture on their own.\n\n[P]Their homeworld is seldom visited due to the difficulty of escaping its gravity well, making Defel rare outside of the Ka'Dedus system. This rarity, combined with their unusual abilities, mean that much of the galaxy believes they are mythical or supernatural beings. Some of the few Defel who leave their homeworld go in search of adventure, and often employ their natural stealth abilities to become assassins, bodyguards, or thieves. Most Defel who leave Af'El, however, are prized more for their skills in metallurgy, and are contracted by smelting operations and starship manufacturers.\n\n[P]The Defel see some trade in meleenium, a rare substance used in durasteel production, which is only found naturally on Af'El. Vulca Minerals sends one ship a year to the Defel to trade fresh food for meleenium.\n\n[P][B]Homeworld:[b] Af'El is the homeworld to the Defel, whom dwell in underground cities. It is a high-gravity planet with no ozone layer, and it orbits the ultraviolet supergiant Ka'Dedus. Because of the lack of ozone, ultraviolet light passed freely to the surface, while other light wavelengths are blocked by the heavy gases in the planet's atmosphere. Thus, all animals on Af'El can only see in ultraviolet light ranges. A main export of the planet is the metal meleenium used in durasteel.\n\n[P]Due to the tremendous velocity necessary for a starship to escape Af'El's gravity well, the planet was rarely visited. It was the only known source of naturally occurring meleenium, and as a result, Vulca Minerals made annual trips to the world. A number of private metallurgists and scientists also visited the world to conduct research.\n\n[P][B]Language:[b] Defel is the official language of Af'El, used by the native Defel species. Defels are not fond of languages other than their own, so most of them do not learn  Galactic Basic Standard unless they have need for it, mainly because they need to leave  Af'El. Ironically, more often than not, it is easy to find a Basic-speaking Defel (other than  the difficult task of finding a Defel at all).",
            "attributes": {
              "Brawn": {
                "mod": "Brawn",
                "modtype": "Characteristic",
                "value": 2,
                "exclude": true,
              },
              "Agility": {
                "mod": "Agility",
                "modtype": "Characteristic",
                "value": 2,
                "exclude": true,
              },
              "Intellect": {
                "mod": "Intellect",
                "modtype": "Characteristic",
                "value": 1,
                "exclude": true,
              },
              "Cunning": {
                "mod": "Cunning",
                "modtype": "Characteristic",
                "value": 3,
                "exclude": true,
              },
              "Willpower": {
                "mod": "Willpower",
                "modtype": "Characteristic",
                "value": 2,
                "exclude": true,
              },
              "Presence": {
                "mod": "Presence",
                "modtype": "Characteristic",
                "value": 2,
                "exclude": true,
              },
              "Wounds": {
                "mod": "Wounds",
                "modtype": "Stat",
                "value": 10,
                "exclude": true,
              },
              "Strain": {
                "mod": "Strain",
                "modtype": "Stat",
                "value": 10,
                "exclude": true,
              },
              "Vigilance": {
                "mod": "Vigilance",
                "modtype": "Skill Rank",
                "value": 1,
                "exclude": false,
              },
            },
            "renderedDesc": "<h4>Abilities</h4><p>Light Sensitive : In bright light, without protective goggles,\n            Defel suffer <span class='dietype starwars setback'>b</span><span class='dietype starwars setback'>b</span> on all skill checks.</p><p>Shadowed : In darkness, Defel gain <span class='dietype starwars boost'>b</span><span class='dietype starwars boost'>b</span>\n            to Stealth checks.</p><p>Reduced Silhouette : Defel have a Silhouette of 0.</p><p></p><h4>Defel</h4>\n\nThe Defel (colloquially known as Wraiths) are barely visible beings native to the Outer Rim planet Af'El who appear to most other species as shadows, re-enforcing the misconception that they are chameleon-like beings or \"living shadows\".\n\n<p><span class='bold'>Physiology:</span> Defel are from Af'El, a large, high-gravity, seldom-visited world orbiting the ultraviolet supergiant Ka'Dedus. Since Af'El has no ozone layer, ultraviolet light passes freely to the surface, while other light wavelengths are mostly blocked by the heavy gases in the planet's atmosphere. Thus, all lifeforms on Af'El can see in ultraviolet light ranges, but are blinded by all but the dimmest light in other wavelengths. This is why Defels normally wear a visor when they leave Af'El, and expect to be exposed to daylight at their destination. Compared to other species, they can see exceptionally well in the dark.\n\n</p><p>Defel are short, stocky beings, averaging 1.3 meters tall and nearly as wide. Though they are nearly invisible in normal light, Defel are actually colorful beings. Viewed under ultraviolet light, their fur appear in colors ranging from yellow to blue. Their snouts appear green, with orange, gill-like slits at the base of their jawlines. Elderly Defel lose their ability to absorb light, fading to a dull dark brown under visible light.\n\n</p><p><span class='bold'>Society:</span> Due to the harsh conditions of Af'El, Defel have a society based on communal resource sharing. Co-operation is vital for survival. As a result, the typical Defel is a tough, independent being, with a strong sense of honor. Defel stand by their word, and refuse to associate with anyone who has broken a promise. The Defel live in underground cities to escape Af'El's violent storms. Their subterranean society has developed highly advanced mining and metallurgical technology, though they have not developed space travel or agriculture on their own.\n\n</p><p>Their homeworld is seldom visited due to the difficulty of escaping its gravity well, making Defel rare outside of the Ka'Dedus system. This rarity, combined with their unusual abilities, mean that much of the galaxy believes they are mythical or supernatural beings. Some of the few Defel who leave their homeworld go in search of adventure, and often employ their natural stealth abilities to become assassins, bodyguards, or thieves. Most Defel who leave Af'El, however, are prized more for their skills in metallurgy, and are contracted by smelting operations and starship manufacturers.\n\n</p><p>The Defel see some trade in meleenium, a rare substance used in durasteel production, which is only found naturally on Af'El. Vulca Minerals sends one ship a year to the Defel to trade fresh food for meleenium.\n\n</p><p><span class='bold'>Homeworld:</span> Af'El is the homeworld to the Defel, whom dwell in underground cities. It is a high-gravity planet with no ozone layer, and it orbits the ultraviolet supergiant Ka'Dedus. Because of the lack of ozone, ultraviolet light passed freely to the surface, while other light wavelengths are blocked by the heavy gases in the planet's atmosphere. Thus, all animals on Af'El can only see in ultraviolet light ranges. A main export of the planet is the metal meleenium used in durasteel.\n\n</p><p>Due to the tremendous velocity necessary for a starship to escape Af'El's gravity well, the planet was rarely visited. It was the only known source of naturally occurring meleenium, and as a result, Vulca Minerals made annual trips to the world. A number of private metallurgists and scientists also visited the world to conduct research.\n\n</p><p><span class='bold'>Language:</span> Defel is the official language of Af'El, used by the native Defel species. Defels are not fond of languages other than their own, so most of them do not learn  Galactic Basic Standard unless they have need for it, mainly because they need to leave  Af'El. Ironically, more often than not, it is easy to find a Basic-speaking Defel (other than  the difficult task of finding a Defel at all).</p>",
          },
          "flags": {
            "importid": "DEFEL",
          },
          "img": "modules/starwarsffg-compendiums/images/packs/oggdudespecies/DEFEL.png",
          "effects": [],
        },
        {
          "_id": "WOIux8jzLP1QZYEl",
          "name": "Shii-Cho Knight",
          "type": "specialization",
          "data": {
            "description": "[H4]Shii-Cho Knight[h4]\n\nThe ancient lightsaber fighting style of Shii-Cho is said to be the first lightsaber form taught to the Jedi and their predecessors. It focuses on the essentials of saber fighting and borrows heavily from other sword fighting techniques. Appropriately, the modern practitioners of this form focus on perfecting the core tenants of sword fighting, recognizing the strength of simplicity. Shii-Cho Knights eschew fancy maneuvers, preferring to focus on the fundamentals of block, parry. and strike.\n\n[P]Shii-Cho Knights acquire [B]Athletics, Coordination, Lightsaber,[b] and [B]Melee[b] as additional career skills. If this is the character's starting specialization, he may choose two of these skills and gain one free rank in each, without spending starting experience. These skills provide them with a solid grounding in the core techniques of any physical conflict. They are familiar with the weapon they wield, but they are also very comfortable exploiting their natural athleticism and flexibility. Because of this, they can not only avoid an enemy's attack, but also make certain that they are able to strike effectively when their target is at a disadvantage.\n\n[P]Followers of this path are seldom concerned with personal appearances or the style that they exhibit in a conflict. Instead, they are focused on precision and on achieving their ultimate goal of victory. For them, a solid grounding in the basics is something they can rely on in any situation. When lives are on the line, they devote their attention to executing their maneuvers in a traditional way, using them to counter an opponent while simultaneously restricting his options.",
            "attributes": {
              "attr1": {
                "mod": "Athletics",
                "modtype": "Career Skill",
                "value": true,
              },
              "attr2": {
                "mod": "Athletics",
                "modtype": "Skill Rank",
                "value": 0,
              },
              "attr3": {
                "mod": "Coordination",
                "modtype": "Career Skill",
                "value": true,
              },
              "attr4": {
                "mod": "Coordination",
                "modtype": "Skill Rank",
                "value": 0,
              },
              "attr5": {
                "mod": "Lightsaber",
                "modtype": "Career Skill",
                "value": true,
              },
              "attr6": {
                "mod": "Lightsaber",
                "modtype": "Skill Rank",
                "value": 1,
                "key": "Lightsaber",
              },
              "attr7": {
                "mod": "Melee",
                "modtype": "Career Skill",
                "value": true,
              },
              "attr8": {
                "mod": "Melee",
                "modtype": "Skill Rank",
                "value": 1,
                "key": "Melee",
              },
              "attrForceRating": {
                "mod": "ForcePool",
                "modtype": "Stat",
                "value": 1,
              },
            },
            "talents": {
              "talent0": {
                "name": "Parry",
                "description": "When hit by a melee attack, suffer 3 strain to reduce damage by 2 plus ranks in Parry.",
                "activation": "Active (Incidental, Out of Turn)",
                "activationLabel": "SWFFG.TalentActivationsActiveIncidentalOutofTurn",
                "isForceTalent": false,
                "isRanked": true,
                "size": "single",
                "canLinkTop": true,
                "canLinkRight": true,
                "itemId": "EFL2xt5A365PdhfQ",
                "attributes": {},
                "pack": "world.oggdudetalents",
                "isConflictTalent": false,
                "rank": 1,
                "islearned": true,
                "cost": "5",
                "links-top-1": false,
                "links-right": false,
                "visible": true,
                "canSplit": false,
                "canCombine": true,
              },
              "talent1": {
                "name": "Second Wind",
                "description": "Once per encounter, may use Second Wind incidental to heal strain equal to ranks in Second Wind.",
                "activation": "Active (Incidental)",
                "activationLabel": "SWFFG.TalentActivationsActiveIncidental",
                "isForceTalent": false,
                "isRanked": true,
                "size": "single",
                "canLinkTop": true,
                "canLinkRight": true,
                "itemId": "Jg87sIssUR7t5nP9",
                "attributes": {},
                "pack": "world.oggdudetalents",
                "isConflictTalent": false,
                "rank": 1,
                "islearned": true,
                "cost": "5",
                "links-top-1": false,
                "links-right": false,
                "visible": true,
                "canSplit": false,
                "canCombine": true,
              },
              "talent2": {
                "name": "Toughened",
                "description": "Gain +2 wound threshold.",
                "activation": "Passive",
                "activationLabel": "SWFFG.TalentActivationsPassive",
                "isForceTalent": false,
                "isRanked": true,
                "size": "single",
                "canLinkTop": true,
                "canLinkRight": true,
                "itemId": "pHVUWrmAS4iHuWis",
                "attributes": {
                  "Wounds": {
                    "mod": "Wounds",
                    "modtype": "Stat",
                    "value": "2",
                  },
                },
                "pack": "world.oggdudetalents",
                "isConflictTalent": false,
                "rank": 1,
                "islearned": true,
                "cost": "5",
                "links-top-1": false,
                "links-right": false,
                "visible": true,
                "canSplit": false,
                "canCombine": true,
              },
              "talent3": {
                "name": "Parry",
                "description": "When hit by a melee attack, suffer 3 strain to reduce damage by 2 plus ranks in Parry.",
                "activation": "Active (Incidental, Out of Turn)",
                "activationLabel": "SWFFG.TalentActivationsActiveIncidentalOutofTurn",
                "isForceTalent": false,
                "isRanked": true,
                "size": "single",
                "canLinkTop": true,
                "canLinkRight": false,
                "itemId": "EFL2xt5A365PdhfQ",
                "attributes": {},
                "pack": "world.oggdudetalents",
                "isConflictTalent": false,
                "rank": 1,
                "islearned": true,
                "cost": "5",
                "links-top-1": false,
                "links-right": false,
                "visible": true,
                "canSplit": false,
                "canCombine": false,
              },
              "talent4": {
                "name": "Second Wind",
                "description": "Once per encounter, may use Second Wind incidental to heal strain equal to ranks in Second Wind.",
                "activation": "Active (Incidental)",
                "activationLabel": "SWFFG.TalentActivationsActiveIncidental",
                "isForceTalent": false,
                "isRanked": true,
                "size": "single",
                "canLinkTop": true,
                "canLinkRight": true,
                "itemId": "Jg87sIssUR7t5nP9",
                "attributes": {},
                "links-top-1": true,
                "links-right": true,
                "pack": "world.oggdudetalents",
                "isConflictTalent": false,
                "rank": 1,
                "islearned": true,
                "cost": "10",
                "visible": true,
                "canSplit": false,
                "canCombine": true,
              },
              "talent5": {
                "name": "Conditioned",
                "description": "Remove [SE] per rank of Conditioned from Athletics and Coordination check. Reduce the damage and strain suffered from falling by 1 per rank of Conditioned.",
                "activation": "Passive",
                "activationLabel": "SWFFG.TalentActivationsPassive",
                "isForceTalent": false,
                "isRanked": false,
                "size": "single",
                "canLinkTop": true,
                "canLinkRight": true,
                "itemId": "yvoZZSmBhVV653hW",
                "attributes": {
                  "attr1": {
                    "mod": "Athletics",
                    "modtype": "Skill Remove Setback",
                    "value": "1",
                  },
                  "attr2": {
                    "mod": "Coordination",
                    "modtype": "Skill Remove Setback",
                    "value": "1",
                  },
                  "Athletics": {
                    "mod": "Athletics",
                    "modtype": "Skill Remove Setback",
                    "value": 1,
                  },
                  "Coordination": {
                    "mod": "Coordination",
                    "modtype": "Skill Remove Setback",
                    "value": 1,
                  },
                },
                "links-top-1": true,
                "links-right": true,
                "pack": "world.oggdudetalents",
                "isConflictTalent": false,
                "islearned": false,
                "cost": "10",
                "visible": true,
                "canSplit": false,
                "canCombine": true,
              },
              "talent6": {
                "name": "Multiple Opponents",
                "description": "Add [BO] to Lightsaber, Brawl, and Melee checks when engaged with multiple opponents.",
                "activation": "Passive",
                "activationLabel": "SWFFG.TalentActivationsPassive",
                "isForceTalent": false,
                "isRanked": false,
                "size": "single",
                "canLinkTop": true,
                "canLinkRight": true,
                "itemId": "o5MSc9SAbVFmY3KF",
                "attributes": {},
                "links-top-1": true,
                "pack": "world.oggdudetalents",
                "isConflictTalent": false,
                "rank": 1,
                "islearned": true,
                "cost": "10",
                "links-right": false,
                "visible": true,
                "canSplit": false,
                "canCombine": true,
              },
              "talent7": {
                "name": "Durable",
                "description": "May reduce any Critical Injury suffered by 10 per rank of Durable to a minimum of 1.",
                "activation": "Passive",
                "activationLabel": "SWFFG.TalentActivationsPassive",
                "isForceTalent": false,
                "isRanked": false,
                "size": "single",
                "canLinkTop": true,
                "canLinkRight": false,
                "itemId": "3dxGgVswF83a6qjU",
                "attributes": {},
                "links-top-1": true,
                "pack": "world.oggdudetalents",
                "isConflictTalent": false,
                "islearned": false,
                "cost": "10",
                "links-right": false,
                "visible": true,
                "canSplit": false,
                "canCombine": false,
              },
              "talent8": {
                "name": "Quick Draw",
                "description": "Once per round, draw or holster a weapon or accessible item as an incidental.",
                "activation": "Active (Incidental)",
                "activationLabel": "SWFFG.TalentActivationsActiveIncidental",
                "isForceTalent": false,
                "isRanked": false,
                "size": "single",
                "canLinkTop": true,
                "canLinkRight": true,
                "itemId": "Ae0lmgBU0cdoI7ss",
                "attributes": {},
                "links-top-1": true,
                "pack": "world.oggdudetalents",
                "isConflictTalent": false,
                "islearned": false,
                "cost": "15",
                "links-right": false,
                "visible": true,
                "canSplit": false,
                "canCombine": true,
              },
              "talent9": {
                "name": "Grit",
                "description": "Gain +1 strain threshold",
                "activation": "Passive",
                "activationLabel": "SWFFG.TalentActivationsPassive",
                "isForceTalent": false,
                "isRanked": true,
                "size": "single",
                "canLinkTop": true,
                "canLinkRight": true,
                "itemId": "AMrvdqjdqfqfJQLJ",
                "attributes": {
                  "Strain": {
                    "mod": "Strain",
                    "modtype": "Stat",
                    "value": "1",
                  },
                },
                "links-top-1": true,
                "links-right": true,
                "pack": "world.oggdudetalents",
                "isConflictTalent": false,
                "rank": 1,
                "islearned": true,
                "cost": "15",
                "visible": true,
                "canSplit": false,
                "canCombine": true,
              },
              "talent10": {
                "name": "Parry",
                "description": "When hit by a melee attack, suffer 3 strain to reduce damage by 2 plus ranks in Parry.",
                "activation": "Active (Incidental, Out of Turn)",
                "activationLabel": "SWFFG.TalentActivationsActiveIncidentalOutofTurn",
                "isForceTalent": false,
                "isRanked": true,
                "size": "single",
                "canLinkTop": true,
                "canLinkRight": true,
                "itemId": "EFL2xt5A365PdhfQ",
                "attributes": {},
                "links-top-1": true,
                "links-right": true,
                "pack": "world.oggdudetalents",
                "isConflictTalent": false,
                "rank": 1,
                "islearned": true,
                "cost": "15",
                "visible": true,
                "canSplit": false,
                "canCombine": true,
              },
              "talent11": {
                "name": "Defensive Training",
                "description": "When wielding a Lightsaber, Melee, or Brawl weapon, the weapon gains the Defensive quality with a rating equal to ranks in Defensive Training.",
                "activation": "Passive",
                "activationLabel": "SWFFG.TalentActivationsPassive",
                "isForceTalent": false,
                "isRanked": false,
                "size": "single",
                "canLinkTop": true,
                "canLinkRight": false,
                "itemId": "wXWdbsJt5ILPjrMq",
                "attributes": {},
                "links-top-1": true,
                "pack": "world.oggdudetalents",
                "isConflictTalent": false,
                "islearned": false,
                "cost": "15",
                "links-right": false,
                "visible": true,
                "canSplit": false,
                "canCombine": false,
              },
              "talent12": {
                "name": "Natural Blademaster",
                "description": "Once per session, may reroll any 1 Lightsaber or Melee check.",
                "activation": "Active (Incidental)",
                "activationLabel": "SWFFG.TalentActivationsActiveIncidental",
                "isForceTalent": false,
                "isRanked": false,
                "size": "single",
                "canLinkTop": true,
                "canLinkRight": true,
                "itemId": "O5aGkqYoUrWgpwZi",
                "attributes": {},
                "links-top-1": true,
                "links-right": true,
                "pack": "world.oggdudetalents",
                "isConflictTalent": false,
                "islearned": false,
                "cost": "20",
                "visible": true,
                "canSplit": false,
                "canCombine": true,
              },
              "talent13": {
                "name": "Sarlacc Sweep",
                "description": "Increase difficulty of Lightsaber check by 1 to perform Sarlacc Sweep action. May spend [AD][AD] to hit additional engaged targets.",
                "activation": "Active (Action)",
                "activationLabel": "SWFFG.TalentActivationsActiveAction",
                "isForceTalent": false,
                "isRanked": false,
                "size": "single",
                "canLinkTop": true,
                "canLinkRight": true,
                "itemId": "AChMkpSpNq2TfGss",
                "attributes": {},
                "links-top-1": true,
                "pack": "world.oggdudetalents",
                "isConflictTalent": false,
                "rank": 1,
                "islearned": true,
                "cost": "20",
                "links-right": false,
                "visible": true,
                "canSplit": false,
                "canCombine": true,
              },
              "talent14": {
                "name": "Parry (Improved)",
                "description": "When parrying a hit that generate [DE] or [TH][TH][TH], may hit attacker once with Lightsaber, Brawl, or Melee weapon (dealing base damage) after original attack resolves.",
                "activation": "Active (Incidental, Out of Turn)",
                "activationLabel": "SWFFG.TalentActivationsActiveIncidentalOutofTurn",
                "isForceTalent": false,
                "isRanked": false,
                "size": "single",
                "canLinkTop": true,
                "canLinkRight": true,
                "itemId": "YIttPgrGqB8FMY3j",
                "attributes": {},
                "links-top-1": true,
                "links-right": true,
                "pack": "world.oggdudetalents",
                "isConflictTalent": false,
                "islearned": false,
                "cost": "20",
                "visible": true,
                "canSplit": false,
                "canCombine": true,
              },
              "talent15": {
                "name": "Sum Djem",
                "description": "May spend [TR] or [AD][AD] with a successful Lightsaber check to disarm opponent.",
                "activation": "Passive",
                "activationLabel": "SWFFG.TalentActivationsPassive",
                "isForceTalent": false,
                "isRanked": false,
                "size": "single",
                "canLinkTop": true,
                "canLinkRight": false,
                "itemId": "7ZnTrrlAQHHsh5PC",
                "attributes": {},
                "links-top-1": true,
                "pack": "world.oggdudetalents",
                "isConflictTalent": false,
                "islearned": false,
                "cost": "20",
                "links-right": false,
                "visible": true,
                "canSplit": false,
                "canCombine": false,
              },
              "talent16": {
                "name": "Center of Being",
                "description": "Take a Center of Being maneuver. Until the beginning of next turn, attacks against the character increase their critical rating by 1 per rank of Center of Being.",
                "activation": "Active (Maneuver)",
                "activationLabel": "SWFFG.TalentActivationsActiveManeuver",
                "isForceTalent": false,
                "isRanked": false,
                "size": "single",
                "canLinkTop": true,
                "canLinkRight": true,
                "itemId": "JcFo4dDFjdSHTYVt",
                "attributes": {},
                "links-top-1": true,
                "links-right": true,
                "pack": "world.oggdudetalents",
                "isConflictTalent": false,
                "islearned": false,
                "cost": "25",
                "visible": true,
                "canSplit": false,
                "canCombine": true,
              },
              "talent17": {
                "name": "Durable",
                "description": "May reduce any Critical Injury suffered by 10 per rank of Durable to a minimum of 1.",
                "activation": "Passive",
                "activationLabel": "SWFFG.TalentActivationsPassive",
                "isForceTalent": false,
                "isRanked": true,
                "size": "single",
                "canLinkTop": true,
                "canLinkRight": true,
                "itemId": "3dxGgVswF83a6qjU",
                "attributes": {},
                "links-top-1": true,
                "links-right": true,
                "pack": "world.oggdudetalents",
                "isConflictTalent": false,
                "rank": 1,
                "islearned": true,
                "cost": "25",
                "visible": true,
                "canSplit": false,
                "canCombine": true,
              },
              "talent18": {
                "name": "Dedication",
                "description": "Gain +1 to a single characteristic. This cannot bring a characteristic above 6.",
                "activation": "Passive",
                "activationLabel": "SWFFG.TalentActivationsPassive",
                "isForceTalent": false,
                "isRanked": true,
                "size": "single",
                "canLinkTop": true,
                "canLinkRight": true,
                "itemId": "SsEealnoSAxzud0g",
                "attributes": {
                  "attr1": {
                    "isCheckbox": false,
                    "mod": "Brawn",
                    "modtype": "Characteristic",
                    "value": 1,
                  },
                },
                "links-right": true,
                "pack": "world.oggdudetalents",
                "isConflictTalent": false,
                "rank": 1,
                "islearned": true,
                "cost": "25",
                "links-top-1": false,
                "visible": true,
                "canSplit": false,
                "canCombine": true,
              },
              "talent19": {
                "name": "Parry",
                "description": "When hit by a melee attack, suffer 3 strain to reduce damage by 2 plus ranks in Parry.",
                "activation": "Active (Incidental, Out of Turn)",
                "activationLabel": "SWFFG.TalentActivationsActiveIncidentalOutofTurn",
                "isForceTalent": false,
                "isRanked": false,
                "size": "single",
                "canLinkTop": true,
                "canLinkRight": false,
                "itemId": "EFL2xt5A365PdhfQ",
                "attributes": {},
                "pack": "world.oggdudetalents",
                "isConflictTalent": false,
                "islearned": false,
                "cost": "25",
                "links-top-1": false,
                "links-right": false,
                "visible": true,
                "canSplit": false,
                "canCombine": false,
              },
            },
            "careerskills": {},
            "isEditing": false,
            "renderedDesc": "<h4>Shii-Cho Knight</h4>\n\nThe ancient lightsaber fighting style of Shii-Cho is said to be the first lightsaber form taught to the Jedi and their predecessors. It focuses on the essentials of saber fighting and borrows heavily from other sword fighting techniques. Appropriately, the modern practitioners of this form focus on perfecting the core tenants of sword fighting, recognizing the strength of simplicity. Shii-Cho Knights eschew fancy maneuvers, preferring to focus on the fundamentals of block, parry. and strike.\n\n<p>Shii-Cho Knights acquire <span class='bold'>Athletics, Coordination, Lightsaber,</span> and <span class='bold'>Melee</span> as additional career skills. If this is the character's starting specialization, he may choose two of these skills and gain one free rank in each, without spending starting experience. These skills provide them with a solid grounding in the core techniques of any physical conflict. They are familiar with the weapon they wield, but they are also very comfortable exploiting their natural athleticism and flexibility. Because of this, they can not only avoid an enemy's attack, but also make certain that they are able to strike effectively when their target is at a disadvantage.\n\n</p><p>Followers of this path are seldom concerned with personal appearances or the style that they exhibit in a conflict. Instead, they are focused on precision and on achieving their ultimate goal of victory. For them, a solid grounding in the basics is something they can rely on in any situation. When lives are on the line, they devote their attention to executing their maneuvers in a traditional way, using them to counter an opponent while simultaneously restricting his options.</p>",
          },
          "sort": 100000,
          "flags": {
            "importid": "SHIICHO",
          },
          "img": "icons/svg/mystery-man.svg",
          "effects": [],
          "talentList": [
            {
              "name": "Parry",
              "description": "When hit by a melee attack, suffer 3 strain to reduce damage by 2 plus ranks in Parry.",
              "activation": "Active (Incidental, Out of Turn)",
              "activationLabel": "SWFFG.TalentActivationsActiveIncidentalOutofTurn",
              "isForceTalent": false,
              "isRanked": true,
              "size": "single",
              "canLinkTop": true,
              "canLinkRight": true,
              "itemId": "EFL2xt5A365PdhfQ",
              "attributes": {},
              "pack": "world.oggdudetalents",
              "isConflictTalent": false,
              "rank": 3,
              "islearned": true,
              "cost": "5",
              "links-top-1": false,
              "links-right": false,
            },
            {
              "name": "Second Wind",
              "description": "Once per encounter, may use Second Wind incidental to heal strain equal to ranks in Second Wind.",
              "activation": "Active (Incidental)",
              "activationLabel": "SWFFG.TalentActivationsActiveIncidental",
              "isForceTalent": false,
              "isRanked": true,
              "size": "single",
              "canLinkTop": true,
              "canLinkRight": true,
              "itemId": "Jg87sIssUR7t5nP9",
              "attributes": {},
              "pack": "world.oggdudetalents",
              "isConflictTalent": false,
              "rank": 2,
              "islearned": true,
              "cost": "5",
              "links-top-1": false,
              "links-right": false,
            },
            {
              "name": "Toughened",
              "description": "Gain +2 wound threshold.",
              "activation": "Passive",
              "activationLabel": "SWFFG.TalentActivationsPassive",
              "isForceTalent": false,
              "isRanked": true,
              "size": "single",
              "canLinkTop": true,
              "canLinkRight": true,
              "itemId": "pHVUWrmAS4iHuWis",
              "attributes": {
                "Wounds": {
                  "mod": "Wounds",
                  "modtype": "Stat",
                  "value": "2",
                },
              },
              "pack": "world.oggdudetalents",
              "isConflictTalent": false,
              "rank": 1,
              "islearned": true,
              "cost": "5",
              "links-top-1": false,
              "links-right": false,
            },
            {
              "name": "Multiple Opponents",
              "description": "Add [BO] to Lightsaber, Brawl, and Melee checks when engaged with multiple opponents.",
              "activation": "Passive",
              "activationLabel": "SWFFG.TalentActivationsPassive",
              "isForceTalent": false,
              "isRanked": false,
              "size": "single",
              "canLinkTop": true,
              "canLinkRight": true,
              "itemId": "o5MSc9SAbVFmY3KF",
              "attributes": {},
              "links-top-1": true,
              "pack": "world.oggdudetalents",
              "isConflictTalent": false,
              "rank": "N/A",
              "islearned": true,
              "cost": "10",
              "links-right": false,
            },
            {
              "name": "Grit",
              "description": "Gain +1 strain threshold",
              "activation": "Passive",
              "activationLabel": "SWFFG.TalentActivationsPassive",
              "isForceTalent": false,
              "isRanked": true,
              "size": "single",
              "canLinkTop": true,
              "canLinkRight": true,
              "itemId": "AMrvdqjdqfqfJQLJ",
              "attributes": {
                "Strain": {
                  "mod": "Strain",
                  "modtype": "Stat",
                  "value": "1",
                },
              },
              "links-top-1": true,
              "links-right": true,
              "pack": "world.oggdudetalents",
              "isConflictTalent": false,
              "rank": 1,
              "islearned": true,
              "cost": "15",
            },
            {
              "name": "Sarlacc Sweep",
              "description": "Increase difficulty of Lightsaber check by 1 to perform Sarlacc Sweep action. May spend [AD][AD] to hit additional engaged targets.",
              "activation": "Active (Action)",
              "activationLabel": "SWFFG.TalentActivationsActiveAction",
              "isForceTalent": false,
              "isRanked": false,
              "size": "single",
              "canLinkTop": true,
              "canLinkRight": true,
              "itemId": "AChMkpSpNq2TfGss",
              "attributes": {},
              "links-top-1": true,
              "pack": "world.oggdudetalents",
              "isConflictTalent": false,
              "rank": "N/A",
              "islearned": true,
              "cost": "20",
              "links-right": false,
            },
            {
              "name": "Durable",
              "description": "May reduce any Critical Injury suffered by 10 per rank of Durable to a minimum of 1.",
              "activation": "Passive",
              "activationLabel": "SWFFG.TalentActivationsPassive",
              "isForceTalent": false,
              "isRanked": true,
              "size": "single",
              "canLinkTop": true,
              "canLinkRight": true,
              "itemId": "3dxGgVswF83a6qjU",
              "attributes": {},
              "links-top-1": true,
              "links-right": true,
              "pack": "world.oggdudetalents",
              "isConflictTalent": false,
              "rank": 1,
              "islearned": true,
              "cost": "25",
            },
            {
              "name": "Dedication",
              "description": "Gain +1 to a single characteristic. This cannot bring a characteristic above 6.",
              "activation": "Passive",
              "activationLabel": "SWFFG.TalentActivationsPassive",
              "isForceTalent": false,
              "isRanked": true,
              "size": "single",
              "canLinkTop": true,
              "canLinkRight": true,
              "itemId": "SsEealnoSAxzud0g",
              "attributes": {
                "attr1": {
                  "isCheckbox": false,
                  "mod": "Brawn",
                  "modtype": "Characteristic",
                  "value": 1,
                },
              },
              "links-right": true,
              "pack": "world.oggdudetalents",
              "isConflictTalent": false,
              "rank": 1,
              "islearned": true,
              "cost": "25",
              "links-top-1": false,
            },
          ],
        },
      ];
      chai.expect(ModifierHelpers.getBaseValue(items, "Brawn", "Characteristic")).to.equal(2);
    })
  );
};
